apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  namespace: default
  labels:
    app: django-app
spec:
  replicas: 0
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: first-deployment
        image: akashsingh60/first
        ports:
        - containerPort: 8000